
CREATE TABLE IF NOT EXISTS `BILL_DETAILS`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `PRICE` BIGINT(20)  DEFAULT NULL,
  `QUANTITY` INT(11)  DEFAULT NULL,
  `BILL_ID` BIGINT(20)  DEFAULT NULL,
  `PRODUCT_ID` BIGINT(20)  DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `FK7COOSSDAXTWJPY23KNSJTUA2I`(`BILL_ID`) USING BTREE,
  INDEX `FK4IAGDR0UHSQ4TJ0AG99NMMYA1`(`PRODUCT_ID`) USING BTREE,
  CONSTRAINT `FK4IAGDR0UHSQ4TJ0AG99NMMYA1` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK7COOSSDAXTWJPY23KNSJTUA2I` FOREIGN KEY (`BILL_ID`) REFERENCES `BILL` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
)
