
CREATE TABLE IF NOT EXISTS `APP_USER`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ADDRESS` VARCHAR(255)   DEFAULT NULL,
  `EMAIL` VARCHAR(255)   DEFAULT NULL,
  `FULL_NAME` VARCHAR(255)   DEFAULT NULL,
  `PASSWORD` VARCHAR(255)   DEFAULT NULL,
  `PHONE_NUMBER` VARCHAR(10)   DEFAULT NULL,
  `USERNAME` VARCHAR(255)   DEFAULT NULL,
  `ROLL_ID` BIGINT(20)  DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `UK_3K4CPLVH82SRUEUTTFKWNYLQ0`(`USERNAME`) USING BTREE,
  INDEX `FK2NP9BJ4MEDBDFWWFDX5KUV5VI`(`ROLL_ID`) USING BTREE,
  CONSTRAINT `FK2NP9BJ4MEDBDFWWFDX5KUV5VI` FOREIGN KEY (`ROLL_ID`) REFERENCES `APP_ROLE` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
)
