
CREATE TABLE IF NOT EXISTS `PRODUCTS`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `DESCRIPTION` LONGTEXT  NULL,
  `IMAGE1` VARCHAR(255)   DEFAULT NULL,
  `IMAGE2` VARCHAR(255)   DEFAULT NULL,
  `IMAGE3` VARCHAR(255)   DEFAULT NULL,
  `IMAGE4` VARCHAR(255)   DEFAULT NULL,
  `NAME` VARCHAR(255)   DEFAULT NULL,
  `PRICE` DOUBLE  DEFAULT NULL,
  `QUANTITY` BIGINT(20)  DEFAULT NULL,
  `CATEGORYS_ID` BIGINT(20)  DEFAULT NULL,
  `TRADEMARK_ID` BIGINT(20)  DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `FK3YRCDOOLP5HQ5N3LSS2DETS7O`(`CATEGORYS_ID`) USING BTREE,
  INDEX `FKM6Q3KUG3JV5TP9W7O190244E`(`TRADEMARK_ID`) USING BTREE,
  CONSTRAINT `FK3YRCDOOLP5HQ5N3LSS2DETS7O` FOREIGN KEY (`CATEGORYS_ID`) REFERENCES `CATEGORY` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
CONSTRAINT `FKM6Q3KUG3JV5TP9W7O190244E` FOREIGN KEY (`TRADEMARK_ID`) REFERENCES `TRADE_MARK` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
)
