
CREATE TABLE IF NOT EXISTS `COMMENT`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `COMMENT` VARCHAR(255)  DEFAULT NULL,
  `TIMESTAMP` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP(),
  `PRODUCT_ID` BIGINT(20)  DEFAULT NULL,
  `USER_ID` BIGINT(20)  DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `FKN6RSQAMN9J2VU20IET0ICYA61`(`PRODUCT_ID`) USING BTREE,
  INDEX `FK37MJVNVPWBQDPEWM39Q75H9Q`(`USER_ID`) USING BTREE,
  CONSTRAINT `FK37MJVNVPWBQDPEWM39Q75H9Q` FOREIGN KEY (`USER_ID`) REFERENCES `APP_USER` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FKN6RSQAMN9J2VU20IET0ICYA61` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
)
