
CREATE TABLE IF NOT EXISTS `CART_ITEM`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `QUANTITY` INT(11) NOT NULL,
  `CART_ID` BIGINT(20)  DEFAULT NULL,
  `PRODUCT_ID` BIGINT(20)  DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `FK1UOBYHGL1WVGT1JPCCIA8XXS3`(`CART_ID`) USING BTREE,
  INDEX `FKQKQMVKMBTIAQN2NFQF25YMFS2`(`PRODUCT_ID`) USING BTREE,
  CONSTRAINT `FK1UOBYHGL1WVGT1JPCCIA8XXS3` FOREIGN KEY (`CART_ID`) REFERENCES `CART` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FKQKQMVKMBTIAQN2NFQF25YMFS2` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
)
