
CREATE TABLE IF NOT EXISTS `CART`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `APP_USER_ID` BIGINT(20)  DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `FK3EC32JI648PFTLDNV912B7NG`(`APP_USER_ID`) USING BTREE,
  CONSTRAINT `FK3EC32JI648PFTLDNV912B7NG` FOREIGN KEY (`APP_USER_ID`) REFERENCES `APP_USER` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
)
