INSERT INTO PRODUCTS(ID , DESCRIPTION, IMAGE1,IMAGE2,IMAGE3,IMAGE4, NAME, PRICE, QUANTITY, CATEGORYS_ID, TRADEMARK_ID)
VALUES (1, "ruou loai 1",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/bacadi-1.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/bacardi.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/bacardi-carta-range-205x300.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/ảnh-.png",
        "ruou loai 1", 100, 100, "1", "1"),
       (2, "ruou loai 2",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/chivas-18-blue-hq-2021-3.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/chivas-18-blue-signature-hop-qua-2021.png",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/chivas-25.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/ruou-chivas-extra-13-nam-american-rye-cask-250x250.png",
         "ruou loai 2", 90, 90, "2", "2"),
       (3, "ruou loai 3",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/ruou-vodka-hanoi-700-ml.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/ruou-vodka-nga-russian-standard-vodka-original.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/bacardi-carta-range-205x300.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/bacardi-carta-range-205x300.jpg",
         "ruou loai 3", 80, 80, "3", "3"),
       (4, "ruou loai 4",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/malibu_dua.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/Martini-Bianco-100cl.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/Martini-Extra-Dry-100cl.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/MIGRANT.png",
         "ruou loai 4", 70, 70, "4", "4"),
       (5, "ruou loai 5",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/ruou-chivas21-nam-510x480.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/ruou-chivas-38-nam-min.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/ruou-chivas-62-gun-salute.jpg",
        "C:/Users/thanhlh/Desktop/hust/project3/src/main/resources/static/views/img/ruou-chivas-21-hop-qua-tet-2021-v1.png",
         "ruou loai 5", 60, 60, "5", "5");